name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker image
      run: |
        docker build -t calculator-app:${GITHUB_SHA::7} .
        docker tag calculator-app:${GITHUB_SHA::7} calculator-app:latest

    - name: Run tests
      run: |
        docker run -d -p 5050:5050 --name calculator-container calculator-app:latest
        sleep 5
        chmod +x test_calculator.sh
        ./test_calculator.sh

    - name: Clean up
      if: always()
      run: |
        docker logs calculator-container || true
        docker stop calculator-container || true
        docker rm calculator-container || true 